// Auto-generated from api-spec/openapi.yaml
// prettier-ignore
export type ApiEndpoint = {
	readonly method: string;
	readonly path: string;
	readonly tag: string;
	readonly summary: string;
	readonly params: readonly {
		readonly name: string;
		readonly in: string;
		readonly required: boolean;
		readonly type: string;
		readonly description?: string;
	}[];
	readonly hasBody: boolean;
};

export const API_ENDPOINTS = {
	healthCheck: {
		method: "GET",
		path: "/healthz",
		tag: "health",
		summary: "Health check",
		params: [],
		hasBody: false,
	},
	getMetrics: {
		method: "GET",
		path: "/metrics",
		tag: "metrics",
		summary: "获取 Prometheus 指标",
		params: [],
		hasBody: false,
	},
	listProjects: {
		method: "GET",
		path: "/projects",
		tag: "projects",
		summary: "获取项目列表",
		params: [
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "keyword",
				in: "query",
				required: false,
				type: "string",
				description: "支持按项目名称或编号模糊搜索",
			},
			{
				name: "page",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
			{
				name: "limit",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	createProject: {
		method: "POST",
		path: "/projects",
		tag: "projects",
		summary: "创建项目",
		params: [],
		hasBody: true,
	},
	getProject: {
		method: "GET",
		path: "/projects/{projectId}",
		tag: "projects",
		summary: "获取项目详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateProject: {
		method: "PUT",
		path: "/projects/{projectId}",
		tag: "projects",
		summary: "更新项目",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteProject: {
		method: "DELETE",
		path: "/projects/{projectId}",
		tag: "projects",
		summary: "删除项目",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	joinProject: {
		method: "POST",
		path: "/projects/join",
		tag: "projects",
		summary: "通过接入码加入项目",
		params: [],
		hasBody: true,
	},
	getProjectStats: {
		method: "GET",
		path: "/projects/{projectId}/stats",
		tag: "projects",
		summary: "获取项目统计",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listUnits: {
		method: "GET",
		path: "/projects/{projectId}/units",
		tag: "units",
		summary: "获取单位工程列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	createUnit: {
		method: "POST",
		path: "/projects/{projectId}/units",
		tag: "units",
		summary: "创建单位工程",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	updateUnit: {
		method: "PUT",
		path: "/projects/{projectId}/units/{unitId}",
		tag: "units",
		summary: "更新单位工程",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "unitId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteUnit: {
		method: "DELETE",
		path: "/projects/{projectId}/units/{unitId}",
		tag: "units",
		summary: "删除单位工程",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "unitId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listDocuments: {
		method: "GET",
		path: "/projects/{projectId}/documents",
		tag: "documents",
		summary: "获取资料列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "unitId",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "category",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	createDocument: {
		method: "POST",
		path: "/projects/{projectId}/documents",
		tag: "documents",
		summary: "创建资料",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getDocument: {
		method: "GET",
		path: "/projects/{projectId}/documents/{documentId}",
		tag: "documents",
		summary: "获取资料详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "documentId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateDocument: {
		method: "PUT",
		path: "/projects/{projectId}/documents/{documentId}",
		tag: "documents",
		summary: "更新资料",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "documentId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteDocument: {
		method: "DELETE",
		path: "/projects/{projectId}/documents/{documentId}",
		tag: "documents",
		summary: "删除资料",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "documentId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	submitDocumentForReview: {
		method: "POST",
		path: "/projects/{projectId}/documents/{documentId}/submit",
		tag: "documents",
		summary: "提交审核",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "documentId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listCompilationInstances: {
		method: "GET",
		path: "/projects/{projectId}/instances",
		tag: "documents",
		summary: "获取编制实例列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "itemId",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "unitId",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	createCompilationInstance: {
		method: "POST",
		path: "/projects/{projectId}/instances",
		tag: "documents",
		summary: "创建编制实例",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getCompilationInstance: {
		method: "GET",
		path: "/projects/{projectId}/instances/{instanceId}",
		tag: "documents",
		summary: "获取编制实例详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "instanceId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateCompilationInstance: {
		method: "PUT",
		path: "/projects/{projectId}/instances/{instanceId}",
		tag: "documents",
		summary: "更新编制实例",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "instanceId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteCompilationInstance: {
		method: "DELETE",
		path: "/projects/{projectId}/instances/{instanceId}",
		tag: "documents",
		summary: "删除编制实例",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "instanceId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getCompilationFormData: {
		method: "GET",
		path: "/projects/{projectId}/instances/{instanceId}/form-data",
		tag: "documents",
		summary: "获取表单数据",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "instanceId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateCompilationFormData: {
		method: "PUT",
		path: "/projects/{projectId}/instances/{instanceId}/form-data",
		tag: "documents",
		summary: "写入表单数据",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "instanceId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteCompilationFormField: {
		method: "DELETE",
		path: "/projects/{projectId}/instances/{instanceId}/form-data/{fieldKey}",
		tag: "documents",
		summary: "删除表单字段",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "instanceId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fieldKey",
				in: "path",
				required: true,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	listReviews: {
		method: "GET",
		path: "/reviews",
		tag: "reviews",
		summary: "获取审核任务列表",
		params: [
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "assignedTo",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getReview: {
		method: "GET",
		path: "/reviews/{reviewId}",
		tag: "reviews",
		summary: "获取审核详情",
		params: [
			{
				name: "reviewId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	approveReview: {
		method: "POST",
		path: "/reviews/{reviewId}/approve",
		tag: "reviews",
		summary: "审核通过",
		params: [
			{
				name: "reviewId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	rejectReview: {
		method: "POST",
		path: "/reviews/{reviewId}/reject",
		tag: "reviews",
		summary: "审核驳回",
		params: [
			{
				name: "reviewId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	generateReviewHints: {
		method: "POST",
		path: "/reviews/hints",
		tag: "reviews",
		summary: "生成审核智能提示",
		params: [],
		hasBody: true,
	},
	archiveProject: {
		method: "POST",
		path: "/projects/{projectId}/archive",
		tag: "archives",
		summary: "归档项目",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	packageProject: {
		method: "POST",
		path: "/projects/{projectId}/package",
		tag: "archives",
		summary: "生成封装包",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getProjectAccessCode: {
		method: "GET",
		path: "/projects/{projectId}/access-code",
		tag: "projects",
		summary: "获取项目接入码和密码（仅项目创建者可查看）",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	resetProjectAccessPassword: {
		method: "POST",
		path: "/projects/{projectId}/access-code/reset",
		tag: "projects",
		summary: "重置项目接入密码（仅项目创建者可操作）",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listProjectMembers: {
		method: "GET",
		path: "/projects/{projectId}/members",
		tag: "project-members",
		summary: "获取项目成员列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	addProjectMember: {
		method: "POST",
		path: "/projects/{projectId}/members",
		tag: "project-members",
		summary: "添加项目成员",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	updateProjectMember: {
		method: "PUT",
		path: "/projects/{projectId}/members/{memberId}",
		tag: "project-members",
		summary: "更新项目成员角色",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "memberId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	removeProjectMember: {
		method: "DELETE",
		path: "/projects/{projectId}/members/{memberId}",
		tag: "project-members",
		summary: "移除项目成员",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "memberId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listUsers: {
		method: "GET",
		path: "/users",
		tag: "users",
		summary: "获取用户列表",
		params: [
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "用户状态 (active, inactive(即闲置))",
			},
			{
				name: "keyword",
				in: "query",
				required: false,
				type: "string",
				description: "按用户名、姓名、邮箱搜索",
			},
		],
		hasBody: false,
	},
	createUser: {
		method: "POST",
		path: "/users",
		tag: "users",
		summary: "创建用户",
		params: [],
		hasBody: true,
	},
	updateUser: {
		method: "PUT",
		path: "/users/{userId}",
		tag: "users",
		summary: "更新用户",
		params: [
			{
				name: "userId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteUser: {
		method: "DELETE",
		path: "/users/{userId}",
		tag: "users",
		summary: "删除用户",
		params: [
			{
				name: "userId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	resetUserPassword: {
		method: "POST",
		path: "/users/{userId}/reset-password",
		tag: "users",
		summary: "重置用户密码",
		params: [
			{
				name: "userId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	bindUserTenant: {
		method: "PUT",
		path: "/users/{userId}/bind-tenant",
		tag: "users",
		summary: "将公共用户池用户绑定到租户",
		params: [
			{
				name: "userId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	listDepartments: {
		method: "GET",
		path: "/departments",
		tag: "departments",
		summary: "获取部门列表",
		params: [],
		hasBody: false,
	},
	createDepartment: {
		method: "POST",
		path: "/departments",
		tag: "departments",
		summary: "创建部门",
		params: [],
		hasBody: true,
	},
	updateDepartment: {
		method: "PUT",
		path: "/departments/{id}",
		tag: "departments",
		summary: "修改部门",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteDepartment: {
		method: "DELETE",
		path: "/departments/{id}",
		tag: "departments",
		summary: "删除部门",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listTemplates: {
		method: "GET",
		path: "/templates",
		tag: "templates",
		summary: "获取模板列表",
		params: [
			{
				name: "category",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	enableTemplate: {
		method: "POST",
		path: "/templates/{id}/enable",
		tag: "templates",
		summary: "启用标准模板并同步到所有租户",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	disableTemplate: {
		method: "POST",
		path: "/templates/{id}/disable",
		tag: "templates",
		summary: "停用标准模板",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getDashboardStats: {
		method: "GET",
		path: "/dashboard/stats",
		tag: "projects",
		summary: "获取仪表盘统计数据",
		params: [],
		hasBody: false,
	},
	login: {
		method: "POST",
		path: "/auth/login",
		tag: "auth",
		summary: "用户登录",
		params: [],
		hasBody: true,
	},
	register: {
		method: "POST",
		path: "/auth/register",
		tag: "auth",
		summary: "用户注册",
		params: [],
		hasBody: true,
	},
	refreshToken: {
		method: "POST",
		path: "/auth/refresh",
		tag: "auth",
		summary: "刷新 AccessToken",
		params: [],
		hasBody: true,
	},
	logout: {
		method: "POST",
		path: "/auth/logout",
		tag: "auth",
		summary: "登出",
		params: [],
		hasBody: true,
	},
	getMe: {
		method: "GET",
		path: "/auth/me",
		tag: "auth",
		summary: "获取当前登录用户信息",
		params: [],
		hasBody: false,
	},
	listSeals: {
		method: "GET",
		path: "/seals",
		tag: "seals",
		summary: "获取印章列表",
		params: [],
		hasBody: false,
	},
	createSeal: {
		method: "POST",
		path: "/seals",
		tag: "seals",
		summary: "创建印章",
		params: [],
		hasBody: true,
	},
	getSealStats: {
		method: "GET",
		path: "/seals/stats",
		tag: "seals",
		summary: "印章统计",
		params: [],
		hasBody: false,
	},
	listMySeals: {
		method: "GET",
		path: "/seals/my",
		tag: "seals",
		summary: "获取当前用户的签章认证记录",
		params: [],
		hasBody: false,
	},
	approveSeal: {
		method: "PUT",
		path: "/seals/{id}/approve",
		tag: "seals",
		summary: "审批通过签章认证",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	rejectSeal: {
		method: "PUT",
		path: "/seals/{id}/reject",
		tag: "seals",
		summary: "拒绝签章认证",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	updateSeal: {
		method: "PUT",
		path: "/seals/{id}",
		tag: "seals",
		summary: "更新印章",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteSeal: {
		method: "DELETE",
		path: "/seals/{id}",
		tag: "seals",
		summary: "删除印章",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listTenants: {
		method: "GET",
		path: "/tenants",
		tag: "tenants",
		summary: "获取租户列表",
		params: [],
		hasBody: false,
	},
	createTenant: {
		method: "POST",
		path: "/tenants",
		tag: "tenants",
		summary: "创建租户",
		params: [],
		hasBody: true,
	},
	getTenantStats: {
		method: "GET",
		path: "/tenants/stats",
		tag: "tenants",
		summary: "租户统计数据",
		params: [],
		hasBody: false,
	},
	updateTenant: {
		method: "PUT",
		path: "/tenants/{id}",
		tag: "tenants",
		summary: "更新租户",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteTenant: {
		method: "DELETE",
		path: "/tenants/{id}",
		tag: "tenants",
		summary: "删除租户",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listPositions: {
		method: "GET",
		path: "/system/positions",
		tag: "system",
		summary: "获取岗位列表",
		params: [],
		hasBody: false,
	},
	createPosition: {
		method: "POST",
		path: "/system/positions",
		tag: "system",
		summary: "创建岗位",
		params: [],
		hasBody: true,
	},
	listRoles: {
		method: "GET",
		path: "/system/roles",
		tag: "system",
		summary: "获取角色列表",
		params: [],
		hasBody: false,
	},
	createRole: {
		method: "POST",
		path: "/system/roles",
		tag: "system",
		summary: "创建角色",
		params: [],
		hasBody: true,
	},
	listMenus: {
		method: "GET",
		path: "/system/menus",
		tag: "system",
		summary: "获取菜单列表",
		params: [],
		hasBody: false,
	},
	createMenu: {
		method: "POST",
		path: "/system/menus",
		tag: "system",
		summary: "创建菜单",
		params: [],
		hasBody: true,
	},
	listDictionaries: {
		method: "GET",
		path: "/system/dictionaries",
		tag: "system",
		summary: "获取字典列表",
		params: [],
		hasBody: false,
	},
	createDictionary: {
		method: "POST",
		path: "/system/dictionaries",
		tag: "system",
		summary: "创建字典",
		params: [],
		hasBody: true,
	},
	listNotices: {
		method: "GET",
		path: "/system/notices",
		tag: "system",
		summary: "获取公告列表",
		params: [],
		hasBody: false,
	},
	createNotice: {
		method: "POST",
		path: "/system/notices",
		tag: "system",
		summary: "创建公告",
		params: [],
		hasBody: true,
	},
	listOperationLogs: {
		method: "GET",
		path: "/system/logs",
		tag: "system",
		summary: "获取操作日志列表",
		params: [
			{
				name: "limit",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	createOperationLog: {
		method: "POST",
		path: "/system/logs",
		tag: "system",
		summary: "创建操作日志",
		params: [],
		hasBody: true,
	},
	listEnterprises: {
		method: "GET",
		path: "/enterprises",
		tag: "enterprises",
		summary: "获取企业列表",
		params: [],
		hasBody: false,
	},
	createEnterprise: {
		method: "POST",
		path: "/enterprises",
		tag: "enterprises",
		summary: "创建企业",
		params: [],
		hasBody: true,
	},
	getEnterprise: {
		method: "GET",
		path: "/enterprises/{id}",
		tag: "enterprises",
		summary: "获取企业详情",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateEnterprise: {
		method: "PUT",
		path: "/enterprises/{id}",
		tag: "enterprises",
		summary: "更新企业",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteEnterprise: {
		method: "DELETE",
		path: "/enterprises/{id}",
		tag: "enterprises",
		summary: "删除企业",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listSigningTasks: {
		method: "GET",
		path: "/signing-tasks",
		tag: "signing",
		summary: "获取签章任务列表",
		params: [
			{
				name: "projectId",
				in: "query",
				required: false,
				type: "integer",
				description: "",
			},
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	createSigningTask: {
		method: "POST",
		path: "/signing-tasks",
		tag: "signing",
		summary: "创建签章任务",
		params: [],
		hasBody: true,
	},
	getSigningTask: {
		method: "GET",
		path: "/signing-tasks/{id}",
		tag: "signing",
		summary: "获取签章任务详情",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateSigningTask: {
		method: "PUT",
		path: "/signing-tasks/{id}",
		tag: "signing",
		summary: "更新签章任务",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteSigningTask: {
		method: "DELETE",
		path: "/signing-tasks/{id}",
		tag: "signing",
		summary: "删除签章任务",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateSigningNode: {
		method: "PUT",
		path: "/signing-tasks/{id}/nodes/{nodeId}",
		tag: "signing",
		summary: "更新签章节点",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "nodeId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getMonthlyTrends: {
		method: "GET",
		path: "/dashboard/monthly-trends",
		tag: "projects",
		summary: "获取月度趋势数据",
		params: [],
		hasBody: false,
	},
	getMyDocument: {
		method: "GET",
		path: "/my-document",
		tag: "documents",
		summary: "获取我的资料列表",
		params: [],
		hasBody: false,
	},
	changePassword: {
		method: "PUT",
		path: "/auth/password",
		tag: "auth",
		summary: "修改密码",
		params: [],
		hasBody: true,
	},
	listUploadFiles: {
		method: "GET",
		path: "/projects/{projectId}/uploads",
		tag: "documents",
		summary: "获取上传文件列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "nodeId",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	createUploadFile: {
		method: "POST",
		path: "/projects/{projectId}/uploads",
		tag: "documents",
		summary: "创建上传文件记录",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	uploadFile: {
		method: "POST",
		path: "/projects/{projectId}/uploads/file",
		tag: "documents",
		summary: "上传文件（multipart/form-data）",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getFilePreview: {
		method: "GET",
		path: "/projects/{projectId}/uploads/{fileId}/preview",
		tag: "documents",
		summary: "获取文件预览",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getUploadFile: {
		method: "GET",
		path: "/projects/{projectId}/uploads/{fileId}",
		tag: "documents",
		summary: "获取上传文件详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateUploadFile: {
		method: "PUT",
		path: "/projects/{projectId}/uploads/{fileId}",
		tag: "documents",
		summary: "更新上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteUploadFile: {
		method: "DELETE",
		path: "/projects/{projectId}/uploads/{fileId}",
		tag: "documents",
		summary: "删除上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	renameUploadFile: {
		method: "POST",
		path: "/projects/{projectId}/uploads/{fileId}/rename",
		tag: "documents",
		summary: "重命名上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	replaceUploadFile: {
		method: "POST",
		path: "/projects/{projectId}/uploads/{fileId}/replace",
		tag: "documents",
		summary: "替换上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	listUploadFileVersions: {
		method: "GET",
		path: "/projects/{projectId}/uploads/{fileId}/versions",
		tag: "documents",
		summary: "获取上传文件版本列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getUploadFileVersion: {
		method: "GET",
		path: "/projects/{projectId}/uploads/{fileId}/versions/{versionId}",
		tag: "documents",
		summary: "获取指定版本详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "versionId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	bulkSubmitUploadFiles: {
		method: "POST",
		path: "/projects/{projectId}/uploads/bulk-submit",
		tag: "documents",
		summary: "批量提交上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	collectUploadFile: {
		method: "POST",
		path: "/projects/{projectId}/uploads/{fileId}/collect",
		tag: "documents",
		summary: "采集上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	returnUploadFile: {
		method: "POST",
		path: "/projects/{projectId}/uploads/{fileId}/return",
		tag: "documents",
		summary: "退回上传文件",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "fileId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	listInviteLinks: {
		method: "GET",
		path: "/projects/{projectId}/invites/links",
		tag: "projects",
		summary: "获取邀请链接列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	createInviteLink: {
		method: "POST",
		path: "/projects/{projectId}/invites/links",
		tag: "projects",
		summary: "创建邀请链接",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	revokeInviteLink: {
		method: "PUT",
		path: "/projects/{projectId}/invites/links/{linkId}/revoke",
		tag: "projects",
		summary: "撤销邀请链接",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "linkId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	refreshInviteLink: {
		method: "POST",
		path: "/projects/{projectId}/invites/links/{linkId}/refresh",
		tag: "projects",
		summary: "刷新邀请链接",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "linkId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listInviteMembers: {
		method: "GET",
		path: "/projects/{projectId}/invites/members",
		tag: "projects",
		summary: "获取邀请成员列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	addInviteMember: {
		method: "POST",
		path: "/projects/{projectId}/invites/members",
		tag: "projects",
		summary: "添加邀请成员",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	getInvitePreviewByCode: {
		method: "GET",
		path: "/invite-links/by-code/{code}",
		tag: "invite-links",
		summary: "公开邀请预览",
		params: [
			{
				name: "code",
				in: "path",
				required: true,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	acceptInvite: {
		method: "POST",
		path: "/invite-links/accept",
		tag: "invite-links",
		summary: "接受邀请",
		params: [],
		hasBody: true,
	},
	listArchivePackages: {
		method: "GET",
		path: "/projects/{projectId}/packages",
		tag: "archives",
		summary: "获取归档包列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	createArchivePackage: {
		method: "POST",
		path: "/projects/{projectId}/packages",
		tag: "archives",
		summary: "创建归档包",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	getArchivePackage: {
		method: "GET",
		path: "/projects/{projectId}/packages/{packageId}",
		tag: "archives",
		summary: "获取归档包详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "packageId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateArchivePackage: {
		method: "PUT",
		path: "/projects/{projectId}/packages/{packageId}",
		tag: "archives",
		summary: "更新归档包",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "packageId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteArchivePackage: {
		method: "DELETE",
		path: "/projects/{projectId}/packages/{packageId}",
		tag: "archives",
		summary: "删除归档包",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "packageId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listPrechecks: {
		method: "GET",
		path: "/projects/{projectId}/prechecks",
		tag: "compliance-precheck",
		summary: "获取预检历史列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	runPrecheck: {
		method: "POST",
		path: "/projects/{projectId}/prechecks",
		tag: "compliance-precheck",
		summary: "执行预检",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getLatestPrecheck: {
		method: "GET",
		path: "/projects/{projectId}/prechecks/latest",
		tag: "compliance-precheck",
		summary: "获取最新预检结果",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getPrecheck: {
		method: "GET",
		path: "/projects/{projectId}/prechecks/{precheckId}",
		tag: "compliance-precheck",
		summary: "获取预检详情",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "precheckId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	rerunPrecheck: {
		method: "POST",
		path: "/projects/{projectId}/prechecks/{precheckId}/rerun",
		tag: "compliance-precheck",
		summary: "重新执行预检",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "precheckId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listCollectionItems: {
		method: "GET",
		path: "/projects/{projectId}/collection/items",
		tag: "documents",
		summary: "获取采集项列表",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	createCollectionItem: {
		method: "POST",
		path: "/projects/{projectId}/collection/items",
		tag: "documents",
		summary: "创建采集项",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	updateCollectionItem: {
		method: "PUT",
		path: "/projects/{projectId}/collection/items/{itemId}",
		tag: "documents",
		summary: "更新采集项",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "itemId",
				in: "path",
				required: true,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteCollectionItem: {
		method: "DELETE",
		path: "/projects/{projectId}/collection/items/{itemId}",
		tag: "documents",
		summary: "删除采集项",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "itemId",
				in: "path",
				required: true,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	getCollectionItemStatus: {
		method: "GET",
		path: "/projects/{projectId}/collection/items/{itemId}/status",
		tag: "documents",
		summary: "获取采集项状态",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "itemId",
				in: "path",
				required: true,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	listProjectExtensions: {
		method: "GET",
		path: "/projects/{projectId}/extensions",
		tag: "projects",
		summary: "获取项目扩展字段",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	updateProjectExtensions: {
		method: "PUT",
		path: "/projects/{projectId}/extensions",
		tag: "projects",
		summary: "更新项目扩展字段",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: true,
	},
	listUnitExtensions: {
		method: "GET",
		path: "/projects/{projectId}/extensions/units/{unitId}",
		tag: "units",
		summary: "获取单位工程扩展字段",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "unitId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateUnitExtensions: {
		method: "PUT",
		path: "/projects/{projectId}/extensions/units/{unitId}",
		tag: "units",
		summary: "更新单位工程扩展字段",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "fileType",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
			{
				name: "unitId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	listCatalogTemplates: {
		method: "GET",
		path: "/catalog-templates",
		tag: "templates",
		summary: "获取目录模板列表",
		params: [],
		hasBody: false,
	},
	createCatalogTemplate: {
		method: "POST",
		path: "/catalog-templates",
		tag: "templates",
		summary: "创建目录模板",
		params: [],
		hasBody: true,
	},
	getCatalogTemplate: {
		method: "GET",
		path: "/catalog-templates/{id}",
		tag: "templates",
		summary: "获取目录模板详情",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateCatalogTemplate: {
		method: "PUT",
		path: "/catalog-templates/{id}",
		tag: "templates",
		summary: "更新目录模板",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteCatalogTemplate: {
		method: "DELETE",
		path: "/catalog-templates/{id}",
		tag: "templates",
		summary: "删除目录模板",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listCatalogTemplateNodes: {
		method: "GET",
		path: "/catalog-templates/{id}/nodes",
		tag: "templates",
		summary: "获取目录模板节点列表",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	createCatalogTemplateNode: {
		method: "POST",
		path: "/catalog-templates/{id}/nodes",
		tag: "templates",
		summary: "创建目录模板节点",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	updateCatalogTemplateNode: {
		method: "PUT",
		path: "/catalog-templates/{id}/nodes/{nodeId}",
		tag: "templates",
		summary: "更新目录模板节点",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "nodeId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteCatalogTemplateNode: {
		method: "DELETE",
		path: "/catalog-templates/{id}/nodes/{nodeId}",
		tag: "templates",
		summary: "删除目录模板节点",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "nodeId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listCityArchiveNodes: {
		method: "GET",
		path: "/city-archive/nodes",
		tag: "archives",
		summary: "获取城建归档节点列表",
		params: [],
		hasBody: false,
	},
	createCityArchiveNode: {
		method: "POST",
		path: "/city-archive/nodes",
		tag: "archives",
		summary: "创建城建归档节点",
		params: [],
		hasBody: true,
	},
	getCityArchiveNode: {
		method: "GET",
		path: "/city-archive/nodes/{id}",
		tag: "archives",
		summary: "获取城建归档节点详情",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateCityArchiveNode: {
		method: "PUT",
		path: "/city-archive/nodes/{id}",
		tag: "archives",
		summary: "更新城建归档节点",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteCityArchiveNode: {
		method: "DELETE",
		path: "/city-archive/nodes/{id}",
		tag: "archives",
		summary: "删除城建归档节点",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listCityArchiveMapping: {
		method: "GET",
		path: "/city-archive/mapping",
		tag: "archives",
		summary: "获取城建归档映射列表",
		params: [],
		hasBody: false,
	},
	createCityArchiveMapping: {
		method: "POST",
		path: "/city-archive/mapping",
		tag: "archives",
		summary: "创建城建归档映射",
		params: [],
		hasBody: true,
	},
	deleteCityArchiveMapping: {
		method: "DELETE",
		path: "/city-archive/mapping/{cityNodeId}/{projectNodeId}",
		tag: "archives",
		summary: "删除城建归档映射",
		params: [
			{
				name: "cityNodeId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "projectNodeId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listEnterpriseConfigTemplates: {
		method: "GET",
		path: "/enterprise-configs/templates",
		tag: "templates",
		summary: "获取企业模板配置列表",
		params: [],
		hasBody: false,
	},
	createEnterpriseConfigTemplate: {
		method: "POST",
		path: "/enterprise-configs/templates",
		tag: "templates",
		summary: "创建企业模板配置",
		params: [],
		hasBody: true,
	},
	getEnterpriseConfigTemplate: {
		method: "GET",
		path: "/enterprise-configs/templates/{id}",
		tag: "templates",
		summary: "获取企业模板配置详情",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateEnterpriseConfigTemplate: {
		method: "PUT",
		path: "/enterprise-configs/templates/{id}",
		tag: "templates",
		summary: "更新企业模板配置",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteEnterpriseConfigTemplate: {
		method: "DELETE",
		path: "/enterprise-configs/templates/{id}",
		tag: "templates",
		summary: "删除企业模板配置",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listEnterpriseConfigParadigms: {
		method: "GET",
		path: "/enterprise-configs/paradigms",
		tag: "templates",
		summary: "获取企业范本配置列表",
		params: [],
		hasBody: false,
	},
	createEnterpriseConfigParadigm: {
		method: "POST",
		path: "/enterprise-configs/paradigms",
		tag: "templates",
		summary: "创建企业范本配置",
		params: [],
		hasBody: true,
	},
	getEnterpriseConfigParadigm: {
		method: "GET",
		path: "/enterprise-configs/paradigms/{id}",
		tag: "templates",
		summary: "获取企业范本配置详情",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateEnterpriseConfigParadigm: {
		method: "PUT",
		path: "/enterprise-configs/paradigms/{id}",
		tag: "templates",
		summary: "更新企业范本配置",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteEnterpriseConfigParadigm: {
		method: "DELETE",
		path: "/enterprise-configs/paradigms/{id}",
		tag: "templates",
		summary: "删除企业范本配置",
		params: [
			{
				name: "id",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listTemplateExamples: {
		method: "GET",
		path: "/templates/{templateId}/extras/examples",
		tag: "templates",
		summary: "获取模板范例列表",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	createTemplateExample: {
		method: "POST",
		path: "/templates/{templateId}/extras/examples",
		tag: "templates",
		summary: "创建模板范例",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getTemplateExample: {
		method: "GET",
		path: "/templates/{templateId}/extras/examples/{exampleId}",
		tag: "templates",
		summary: "获取模板范例详情",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "exampleId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateTemplateExample: {
		method: "PUT",
		path: "/templates/{templateId}/extras/examples/{exampleId}",
		tag: "templates",
		summary: "更新模板范例",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "exampleId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	deleteTemplateExample: {
		method: "DELETE",
		path: "/templates/{templateId}/extras/examples/{exampleId}",
		tag: "templates",
		summary: "删除模板范例",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
			{
				name: "exampleId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getTemplateInstructions: {
		method: "GET",
		path: "/templates/{templateId}/extras/instructions",
		tag: "templates",
		summary: "获取模板填写说明",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateTemplateInstructions: {
		method: "PUT",
		path: "/templates/{templateId}/extras/instructions",
		tag: "templates",
		summary: "更新模板填写说明",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	getTemplateAutofillConfig: {
		method: "GET",
		path: "/templates/{templateId}/extras/autofill",
		tag: "templates",
		summary: "获取模板自动填充配置",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	updateTemplateAutofillConfig: {
		method: "PUT",
		path: "/templates/{templateId}/extras/autofill",
		tag: "templates",
		summary: "更新模板自动填充配置",
		params: [
			{
				name: "templateId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: true,
	},
	aiChat: {
		method: "POST",
		path: "/ai/chat",
		tag: "ai",
		summary: "AI对话代理",
		params: [],
		hasBody: true,
	},
	aiTestConnection: {
		method: "POST",
		path: "/ai/test",
		tag: "ai",
		summary: "测试AI连接",
		params: [],
		hasBody: true,
	},
	getAiConfig: {
		method: "GET",
		path: "/ai/config",
		tag: "ai",
		summary: "获取AI配置",
		params: [],
		hasBody: false,
	},
	saveAiConfig: {
		method: "POST",
		path: "/ai/config",
		tag: "ai",
		summary: "保存AI配置",
		params: [],
		hasBody: true,
	},
	deleteAiConfig: {
		method: "DELETE",
		path: "/ai/config",
		tag: "ai",
		summary: "删除AI配置",
		params: [],
		hasBody: false,
	},
	testAiConfig: {
		method: "POST",
		path: "/ai/config/test",
		tag: "ai",
		summary: "测试AI配置",
		params: [],
		hasBody: true,
	},
	aiClassifyFile: {
		method: "POST",
		path: "/ai/classify",
		tag: "ai",
		summary: "AI文件分类",
		params: [],
		hasBody: true,
	},
	aiClassifyFilesBatch: {
		method: "POST",
		path: "/ai/classify/batch",
		tag: "ai",
		summary: "AI批量文件分类",
		params: [],
		hasBody: true,
	},
	aiGetFileTypes: {
		method: "GET",
		path: "/ai/classify/file-types",
		tag: "ai",
		summary: "获取支持的文件类型列表",
		params: [],
		hasBody: false,
	},
	getFormFillDefaults: {
		method: "GET",
		path: "/form-fill/project/{projectId}/defaults",
		tag: "form-fill",
		summary: "获取项目默认填充值",
		params: [
			{
				name: "projectId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	getFormFillSuggestions: {
		method: "POST",
		path: "/form-fill/suggest",
		tag: "form-fill",
		summary: "获取完整填充建议",
		params: [],
		hasBody: true,
	},
	getFormFillHistory: {
		method: "POST",
		path: "/form-fill/history",
		tag: "form-fill",
		summary: "获取基于历史数据的填充建议",
		params: [],
		hasBody: true,
	},
	inferFormFillFields: {
		method: "POST",
		path: "/form-fill/infer",
		tag: "form-fill",
		summary: "AI推断缺失字段",
		params: [],
		hasBody: true,
	},
	batchFormFill: {
		method: "POST",
		path: "/form-fill/batch",
		tag: "form-fill",
		summary: "批量填充",
		params: [],
		hasBody: true,
	},
	listSealFlowTasks: {
		method: "GET",
		path: "/seal-flow",
		tag: "seal-flow",
		summary: "获取当前用户的签章流转任务",
		params: [
			{
				name: "status",
				in: "query",
				required: false,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	signSealFlowNode: {
		method: "POST",
		path: "/seal-flow/{nodeId}/sign",
		tag: "seal-flow",
		summary: "执行签章",
		params: [
			{
				name: "nodeId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	listApiKeys: {
		method: "GET",
		path: "/api-keys",
		tag: "api-keys",
		summary: "列出当前用户的 API Key",
		params: [],
		hasBody: false,
	},
	createApiKey: {
		method: "POST",
		path: "/api-keys",
		tag: "api-keys",
		summary: "创建 API Key",
		params: [],
		hasBody: true,
	},
	revokeApiKey: {
		method: "DELETE",
		path: "/api-keys/{keyId}",
		tag: "api-keys",
		summary: "撤销 API Key",
		params: [
			{
				name: "keyId",
				in: "path",
				required: true,
				type: "integer",
				description: "",
			},
		],
		hasBody: false,
	},
	wechatLogin: {
		method: "POST",
		path: "/wechat/login",
		tag: "wechat",
		summary: "微信小程序登录（code 换 JWT）",
		params: [],
		hasBody: true,
	},
	wechatBind: {
		method: "POST",
		path: "/wechat/bind",
		tag: "wechat",
		summary: "绑定微信账号到当前用户",
		params: [],
		hasBody: true,
	},
	wechatUnbind: {
		method: "DELETE",
		path: "/wechat/bind",
		tag: "wechat",
		summary: "解绑微信账号",
		params: [],
		hasBody: true,
	},
	listWechatBindings: {
		method: "GET",
		path: "/wechat/bindings",
		tag: "wechat",
		summary: "查看当前用户的微信绑定",
		params: [],
		hasBody: false,
	},
	getUserPreference: {
		method: "GET",
		path: "/user/preferences",
		tag: "user-preferences",
		summary: "获取当前用户偏好",
		params: [
			{
				name: "key",
				in: "query",
				required: true,
				type: "string",
				description: "",
			},
		],
		hasBody: false,
	},
	upsertUserPreference: {
		method: "PUT",
		path: "/user/preferences",
		tag: "user-preferences",
		summary: "设置当前用户偏好",
		params: [],
		hasBody: true,
	},
} as const;
